version: '3'

services:
  weather-app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/weather
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1424
    depends_on:
      - postgres

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1424
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: